"""initial tables

Revision ID: 592f3d824edd
Revises: 
Create Date: 2025-08-12 15:36:30.809767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592f3d824edd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('manufacturer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('manufacturer_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicle_categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('registration_stats',
    sa.Column('stat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('registration_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['vehicle_categories.category_id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.manufacturer_id'], ),
    sa.PrimaryKeyConstraint('stat_id'),
    sa.UniqueConstraint('manufacturer_id', 'category_id', 'year', 'quarter', name='uq_registration_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_stats')
    op.drop_table('vehicle_categories')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
